---

- name: Build and run unit and integration tests
  sudo: yes
  sudo_user: "{{ username }}"
  action: command
      chdir=/home/{{ username }}/git
      /usr/bin/mvn clean install -l /tmp/mvn.log~
  environment:
      MAVEN_OPTS: "-Xmx1024m"         
  
- debug: msg="Unit and Integration test executed. Log file writen:/tmp/mvn.log~"  
