---

- hosts: dev
  remote_user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
    - vars/maven_vars.yml
    - ~/.ansible/github_vars.yml
    - vars/ac_vars.yml
    
  tasks:
    - apt: update_cache=yes
    
    - name: Create user
      user: name={{ username }} shell=/bin/bash groups=admin,sudo

    - include: tasks/github.yml
    - include: tasks/git_clone_pull.yml        
    - include: tasks/oracle-jdk8.yml
    - include: tasks/maven.yml
    - include: tasks/compile_test.yml
    
